<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'cms\\Controllers\\index' => 'modules\\cms\\controllers\\index.php',
  'backend\\Controllers\\media' => 'modules\\backend\\controllers\\media.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'rainlab\\blog\\Plugin' => 'plugins\\rainlab\\blog\\Plugin.php',
  'RainLab\\Blog\\Models\\Post' => 'plugins\\rainlab\\blog\\models\\Post.php',
  'RainLab\\Blog\\Classes\\TagProcessor' => 'plugins\\rainlab\\blog\\classes\\TagProcessor.php',
  'RainLab\\Blog\\Models\\Category' => 'plugins\\rainlab\\blog\\models\\Category.php',
  'cms\\Controllers\\themeoptions' => 'modules\\cms\\controllers\\themeoptions.php',
  'RainLab\\Blog\\Components\\Posts' => 'plugins\\rainlab\\blog\\components\\Posts.php',
  'RainLab\\Blog\\Models\\Settings' => 'plugins\\rainlab\\blog\\models\\Settings.php',
  'RainLab\\Blog\\Components\\Post' => 'plugins\\rainlab\\blog\\components\\Post.php',
  'RainLab\\Blog\\Components\\Categories' => 'plugins\\rainlab\\blog\\components\\Categories.php',
  'RainLab\\Blog\\Components\\RssFeed' => 'plugins\\rainlab\\blog\\components\\RssFeed.php',
);